# примеры API-запросов

@baseUrl = http://localhost:8000/api/v1

# создание продукта
POST {{baseUrl}}/products/
Content-Type: application/json

{
  "title": "Помидоры",
  "description": "Лучшие помидоры на рынке"
}

###

# создание продукта
POST {{baseUrl}}/products/
Content-Type: application/json

{
  "title": "Bob",
  "description": "Лучшие помидоры на рынке"
}

###

# получение продуктов
GET {{baseUrl}}/products/
Content-Type: application/json

###

# обновление продукта
PATCH {{baseUrl}}/products/1/
Content-Type: application/json

{
  "description": "Самые сочные и ароматные помидорки"
}

###

# удаление продукта
DELETE {{baseUrl}}/products/4/
Content-Type: application/json

###

# поиск продуктов по названию и описанию
GET {{baseUrl}}/products/?search=помидор
Content-Type: application/json

###

# получение складов
GET {{baseUrl}}/stocks/
Content-Type: application/json

###

# удаление склада
DELETE {{baseUrl}}/stocks/14/
Content-Type: application/json

###

# создание склада
POST {{baseUrl}}/stocks/
Content-Type: application/json

{
  "address": "мой адрес не дом и не улица, мой адрес сегодня такой: www.ленинград-спб.ru3",
  "positions": [
    {
      "product": 2,
      "quantity": 250,
      "price": 120.50
    },
    {
      "product": 3,
      "quantity": 100,
      "price": 180
    }
  ]
}

###

# обновляем записи на складе
PATCH {{baseUrl}}/stocks/16/
Content-Type: application/json

{
  "positions": [
    {
      "product": 2,
      "quantity": 99,
      "price": 79.79
    },
    {
      "product": 3,
      "quantity": 199,
      "price": 78.78
    }
  ]
}

###

# поиск складов, где есть определенный продукт
GET {{baseUrl}}/stocks/?products=2
Content-Type: application/json

###

# поиск складов, где есть определенный продукт
GET {{baseUrl}}/stocks/?search=зел
Content-Type: application/json